/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Buttons: typeof import('./components/Buttons.vue')['default']
    CarCards: typeof import('./components/CarCards.vue')['default']
    CheckBox: typeof import('./components/CheckBox.vue')['default']
    ComboBox: typeof import('./components/ComboBox.vue')['default']
    ComboBoxComponent: typeof import('./components/ComboBoxComponent.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Dialogs: typeof import('./components/Dialogs.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    Inputs: typeof import('./components/Inputs.vue')['default']
    LoginCard: typeof import('./components/LoginCard.vue')['default']
    NoticeStepCard: typeof import('./components/NoticeStepCard.vue')['default']
    RadioButton: typeof import('./components/RadioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./components/Slider.vue')['default']
    StepNavBar: typeof import('./components/StepNavBar.vue')['default']
    StepsAccordion: typeof import('./components/StepsAccordion.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
  }
}
