/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Buttons: typeof import('./components/Buttons.vue')['default']
    CheckBox: typeof import('./components/CheckBox.vue')['default']
    ComboBox: typeof import('./components/ComboBox.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    Inputs: typeof import('./components/Inputs.vue')['default']
    RadioButton: typeof import('./components/RadioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./components/Slider.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
  }
}
